logging:
  level:
    web: TRACE
    org.springframework.web: TRACE

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto: update

myenergi:
  hub.serial: ${MYENERGI_HUB_SERIAL}
  password: ${MYENERGI_PASSWORD}
