spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto: update

myenergi:
  hub.serial: ${MYENERGI_HUB_SERIAL}
  password: ${MYENERGI_PASSWORD}

logging.level.com.zaxxer.hikari: DEBUG